INSERT INTO tab_campanas VALUES (1,'campaña 1',CURRENT_DATE,CURRENT_DATE,CURRENT_USER,CURRENT_DATE);

INSERT INTO tab_encabezado_catalogos VALUES (1,'catalogo enero',CURRENT_DATE,CURRENT_DATE,1,CURRENT_USER,CURRENT_DATE);
INSERT INTO tab_encabezado_catalogos VALUES (2,'catalogo enero - 2',CURRENT_DATE,CURRENT_DATE,1,CURRENT_USER,CURRENT_DATE);